version: '3'
services:
  postgres:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_DB: postgresdb
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    restart: unless-stopped
